// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function AddTagToFile(arg1:number,arg2:number):Promise<void>;

export function CreateTag(arg1:string,arg2:string,arg3:any):Promise<api.Tag>;

export function DeleteTag(arg1:number):Promise<void>;

export function GetFiles(arg1:number,arg2:number):Promise<api.FilePage>;

export function GetThumbnail(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListTags():Promise<Array<api.Tag>>;

export function RemoveTagFromFile(arg1:number,arg2:number):Promise<void>;

export function SelectWorkspace():Promise<api.ScanResult>;
