// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {main} from '../models';

export function AddTagToFile(arg1:number,arg2:number):Promise<void>;

export function AddWorkspaceFolder():Promise<api.ScanResult>;

export function ClearAllTagsFromFile(arg1:number):Promise<void>;

export function CreateTag(arg1:string,arg2:string,arg3:any):Promise<api.Tag>;

export function DeleteTag(arg1:number):Promise<void>;

export function ExecuteOrganize(arg1:api.OrganizeRequest):Promise<api.OrganizeResult>;

export function GetFiles(arg1:number,arg2:number):Promise<api.FilePage>;

export function GetRecentItems():Promise<Array<main.RecentItem>>;

export function GetSettings():Promise<api.AppSettings>;

export function GetThumbnail(arg1:string):Promise<string>;

export function GetWorkspaceFolders():Promise<Array<api.Workspace>>;

export function Greet(arg1:string):Promise<string>;

export function ListTags():Promise<Array<api.Tag>>;

export function LoadWorkspaceConfig():Promise<main.WorkspaceConfig>;

export function OpenRecentItem(arg1:string,arg2:string):Promise<api.ScanResult>;

export function PreviewOrganize(arg1:api.OrganizeRequest):Promise<api.OrganizePreview>;

export function RemoveRecentItem(arg1:string):Promise<void>;

export function RemoveTagFromFile(arg1:number,arg2:number):Promise<void>;

export function RemoveWorkspaceFolder(arg1:number):Promise<void>;

export function RenameFile(arg1:number,arg2:string):Promise<void>;

export function RenameFileWithTags(arg1:number):Promise<void>;

export function SaveWorkspaceConfig(arg1:string,arg2:Array<string>):Promise<string>;

export function ScanWorkspaceFolder(arg1:string):Promise<api.ScanResult>;

export function SearchFilesByTags(arg1:api.FileSearchParams):Promise<api.FilePage>;

export function SelectWorkspace():Promise<api.ScanResult>;

export function SetActiveWorkspace(arg1:number):Promise<void>;

export function ShowStartupDialog():Promise<string>;

export function UndoOrganize(arg1:number):Promise<api.OrganizeUndoResult>;

export function UpdateSettings(arg1:api.AppSettings):Promise<void>;

export function UpdateTagColor(arg1:number,arg2:string):Promise<void>;

export function UpdateWorkspaceConfig(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;
